@startuml

title __DESIGNPATTERNSCA's Class Diagram__\n

  namespace  {
    namespace embers {
      class Members.DiscountCode {
      }
    }
  }
  

  namespace  {
    namespace embers {
      class Members.DriverTest {
      }
    }
  }
  

  namespace  {
    namespace embers {
      class Members.basicMemberDiscount {
      }
    }
  }
  

  namespace  {
    namespace embers {
      class Members.guest {
      }
    }
  }
  

  namespace  {
    namespace embers {
      class Members.longTermMember {
      }
    }
  }
  

  namespace  {
    namespace embers {
      abstract class Members.member {
      }
    }
  }
  

  namespace  {
    namespace embers {
      abstract class Members.memberDecorator {
      }
    }
  }
  

  namespace  {
    namespace embers {
      class Members.overSixtyMember {
      }
    }
  }
  

  namespace  {
    namespace embers {
      class Members.studentMember {
      }
    }
  }
  

  namespace  {
    namespace embers {
      namespace ecorator {
        class MembersDecorator.BasicDiscount {
        }
      }
    }
  }
  

  namespace  {
    namespace embers {
      namespace ecorator {
        abstract class MembersDecorator.DiscountDecorator {
        }
      }
    }
  }
  

  namespace  {
    namespace embers {
      namespace ecorator {
        class MembersDecorator.HalfPrice {
        }
      }
    }
  }
  

  namespace  {
    namespace embers {
      namespace ecorator {
        class MembersDecorator.LoyalDiscount {
        }
      }
    }
  }
  

  namespace  {
    namespace embers {
      namespace ecorator {
        abstract class MembersDecorator.MemberDiscount {
        }
      }
    }
  }
  

  namespace  {
    namespace embers {
      namespace ecorator {
        class MembersDecorator.MemberDiscountDriver {
        }
      }
    }
  }
  

  namespace  {
    namespace embers {
      namespace ecorator {
        class MembersDecorator.OapDiscount {
        }
      }
    }
  }
  

  namespace  {
    namespace embers {
      namespace ecorator {
        class MembersDecorator.SpringClearance {
        }
      }
    }
  }
  

  namespace  {
    namespace embers {
      namespace ecorator {
        class MembersDecorator.StudentDiscount {
        }
      }
    }
  }
  

  namespace  {
    namespace embers {
      namespace ecorator {
        class MembersDecorator.SummerSale {
        }
      }
    }
  }
  

  Members.DiscountCode -up-|> Members.memberDecorator
  Members.basicMemberDiscount -up-|> Members.member
  Members.guest -up-|> Members.member
  Members.longTermMember -up-|> Members.member
  Members.memberDecorator -up-|> Members.member
  Members.memberDecorator o-- Members.member : member
  Members.overSixtyMember -up-|> Members.member
  Members.studentMember -up-|> Members.member
  MembersDecorator.BasicDiscount -up-|> MembersDecorator.MemberDiscount
  MembersDecorator.DiscountDecorator -up-|> MembersDecorator.MemberDiscount
  MembersDecorator.DiscountDecorator o-- MembersDecorator.MemberDiscount : memberDiscount
  MembersDecorator.HalfPrice -up-|> MembersDecorator.DiscountDecorator
  MembersDecorator.LoyalDiscount -up-|> MembersDecorator.MemberDiscount
  MembersDecorator.OapDiscount -up-|> MembersDecorator.MemberDiscount
  MembersDecorator.SpringClearance -up-|> MembersDecorator.DiscountDecorator
  MembersDecorator.StudentDiscount -up-|> MembersDecorator.MemberDiscount
  MembersDecorator.SummerSale -up-|> MembersDecorator.DiscountDecorator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
