@startuml

title __DESIGNPATTERNSCA's Class Diagram__\n

  namespace BookStratagy {
    class BookStratagy.Book {
    }
  }
  

  namespace MemberFactory {
    class MemberFactory.BasicMember {
    }
  }
  

  namespace MemberFactory {
    class MemberFactory.LibraryMember {
    }
  }
  

  namespace MemberFactory {
    class MemberFactory.LoyalMember {
    }
  }
  

  namespace MemberFactory {
    class MemberFactory.Member {
    }
  }
  

  namespace MemberFactory {
    class MemberFactory.MemberFactory {
    }
  }
  

  namespace MemberFactory {
    class MemberFactory.MemberFactoryDriver {
    }
  }
  

  namespace MemberFactory {
    class MemberFactory.OAPMember {
    }
  }
  

  namespace MemberFactory {
    class MemberFactory.StudentMember {
    }
  }
  

  namespace MembersDecorator {
    class MembersDecorator.BasicDiscount {
    }
  }
  

  namespace MembersDecorator {
    abstract class MembersDecorator.DiscountDecorator {
    }
  }
  

  namespace MembersDecorator {
    class MembersDecorator.HalfPrice {
    }
  }
  

  namespace MembersDecorator {
    class MembersDecorator.LoyalDiscount {
    }
  }
  

  namespace MembersDecorator {
    abstract class MembersDecorator.MemberDiscount {
    }
  }
  

  namespace MembersDecorator {
    class MembersDecorator.MemberDiscountDriver {
    }
  }
  

  namespace MembersDecorator {
    class MembersDecorator.OapDiscount {
    }
  }
  

  namespace MembersDecorator {
    class MembersDecorator.SpringClearance {
    }
  }
  

  namespace MembersDecorator {
    class MembersDecorator.StudentDiscount {
    }
  }
  

  namespace MembersDecorator {
    class MembersDecorator.SummerSale {
    }
  }
  

  MemberFactory.BasicMember -up-|> MemberFactory.Member
  MemberFactory.LibraryMember o-- MemberFactory.MemberFactory : factory
  MemberFactory.LoyalMember -up-|> MemberFactory.Member
  MemberFactory.OAPMember -up-|> MemberFactory.Member
  MemberFactory.StudentMember -up-|> MemberFactory.Member
  MembersDecorator.BasicDiscount -up-|> MembersDecorator.MemberDiscount
  MembersDecorator.DiscountDecorator -up-|> MembersDecorator.MemberDiscount
  MembersDecorator.DiscountDecorator o-- MembersDecorator.MemberDiscount : memberDiscount
  MembersDecorator.HalfPrice -up-|> MembersDecorator.DiscountDecorator
  MembersDecorator.LoyalDiscount -up-|> MembersDecorator.MemberDiscount
  MembersDecorator.OapDiscount -up-|> MembersDecorator.MemberDiscount
  MembersDecorator.SpringClearance -up-|> MembersDecorator.DiscountDecorator
  MembersDecorator.StudentDiscount -up-|> MembersDecorator.MemberDiscount
  MembersDecorator.SummerSale -up-|> MembersDecorator.DiscountDecorator


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
